### PR TITLE
fix: allow netcdf forcing

### LINKED ISSUE #134: Allow ngen realizations with NetCDF data providers for forcing
Calibration runs should work with realizations using both CSV and NetCDF providers.

## Current behavior

When using NetCDF provider with an Independent Strategy, an error occurs when ngen_cal tries to create the indepdent catchment definitions in the new realization.  Currently, it tries to create a custom forcing definition and assumes a file pattern substituion is required.  But ngen doesn't allow this kind of structure with NetCDF Providers, so the keys doesn't exist correctly in the global formulation definition which causes an error.

## Expected behavior

Create proper independent realization configurations from input realizations that have a NetCDF provider defined for the global formulation.

### PR DESCRIPTION
**Pull request by aaraney**
closes #134

Add support for forcing files without patterns (e.g. `netcdf`).

### CODE REVIEW

**Comment by aaraney** [comment]
TODO: drop unrelated commits and rebase.

**Comment by aaraney** [comment]
I had @ajkhattak run a test to verify that it worked. Still need to test it out for myself. 

Aside, I would really like to prioritize getting integration tests setup in CI so this could just become a test case.

**Comment by ajkhattak** [comment]
I think I can run a quick test to check if it works with both `.nc` and `.csv` formats, if that would help.

**Comment by aaraney** [comment]
@ajkhattak, yeah that would be great. Thanks for offering!

**Comment by aaraney** [comment]
@ajkhattak, tested and was able to run the model

**Review by hellkite500 — APPROVED** [review]

**Pull request merged**
