### PR TITLE
feat: add lgar, sft, and smp modules

### PR DESCRIPTION
**Pull request by aaraney**
Add nextgen realization models for LGAR, Soil Freeze Thaw, and Soil Moisture Profile modules.

## Additions

- Add nextgen realization models for LGAR, Soil Freeze Thaw, and Soil Moisture Profile modules.

### CODE REVIEW

**Comment by hellkite500** [comment]
Can you add Xia as a coathor to this commit [bc913a3](https://github.com/NOAA-OWP/ngen-cal/pull/97/commits/bc913a3cd1db965d79dbe70a55668f91c6c8fb57) and rebase?

**Comment by aaraney** [comment]
> Can you add Xia as a coathor to this commit [bc913a3](https://github.com/NOAA-OWP/ngen-cal/pull/97/commits/bc913a3cd1db965d79dbe70a55668f91c6c8fb57) and rebase?
> 
> Can add in the commit message trailer. Co-authored-by: Name

Yep, done!

**Comment by aaraney** [comment]
> Add test cases, then we can merge.

Yep, done!

**Review by hellkite500 — APPROVED** [review]

**Comment by hellkite500** [comment]
Thinking about conventional commits, we should maybe adopt a `version(major):`, `version(minor):`, `version(bug)` convention, or some other set of `version(context):` prefixes to help parse history for version changes.  We tend to use a lot of "bump" like commit messages as is, so having a defined set of tags to search for later might be nice.

**Comment by hellkite500** [comment]
Not sure you can ever get away from commits which change some text in the repo based on a version change. E.g change logs, release notes, ect. My previous comment was simply about a commit prefix that helps track down version info changes in the history using conventional commit strategies.

I agree git tags would be helpful, and a set of version commit prefixes may be prime candidates for which commits get tagged!

**Comment by stcui007** [comment]
Depending on your intention, "TGS" might be a more appropriate variable
for  "ground_temperature".

**Pull request merged**
