### PR TITLE
Add `urban_decimal_fraction` cfe parameter

### PR DESCRIPTION
**Pull request by aaraney**
## Changes

- Add `urban_decimal_fraction` cfe parameter. This is only required when `surface_partitioning_scheme=Xinanjiang`.

## Checklist

- [x] PR has an informative and human-readable title
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code can be automatically merged (no conflicts)
- [x] Code follows project standards (link if applicable)
- [x] Passes all existing automated tests
- [x] Any _change_ in functionality is tested
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged / future todos are captured in comments
- [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
- [x] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

### CODE REVIEW

**Comment by aaraney** [comment]
`urban_decimal_fraction` was added here https://github.com/NOAA-OWP/cfe/pull/49. There is an argument that `CFEXinanjiang` data model should make this an optional parameter since there is `cfe` source code that can run with `Xinanjiang` without `urban_decimal_fraction`. My gut feeling is that since there is not a "stable" version of `cfe` it is okay to introduce this potentially breaking change as people who use `cfe` will need to update their workflows to use the new version anyways.

**Comment by hellkite500** [comment]
Pretty sure CFE master can run with either option still?

**Comment by aaraney** [comment]
It doesnt look like it:

https://github.com/NOAA-OWP/cfe/blob/042fc1bbe5debf3234e2e8319d3598a9b9f50a70/src/bmi_cfe.c#L781-L784

https://github.com/NOAA-OWP/cfe/blob/042fc1bbe5debf3234e2e8319d3598a9b9f50a70/src/bmi_cfe.c#L962

**Comment by hellkite500** [comment]
My comment was misguided, I read the intent as making this required for all runoff schemes, which isn't what's happening.

**Review by hellkite500 — APPROVED** [review]

**Pull request merged**
